server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/database_dev
    username: devuser
    password: dev@USER25
    driver-class-name: org.postgresql.Driver
  jpa:
      hibernate:
          ddl-auto: update # Options: none, validate, update, create, create-drop
      show-sql: true
      properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect

upload:
  path: uploads

frontend:
  url: http://localhost:3000